// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: poolmgr/v1alpha1/pooladmin.proto

package poolmgrv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolAdmin_CreatePool_FullMethodName = "/poolmgr.v1alpha1.PoolAdmin/CreatePool"
	PoolAdmin_UpdatePool_FullMethodName = "/poolmgr.v1alpha1.PoolAdmin/UpdatePool"
	PoolAdmin_DeletePool_FullMethodName = "/poolmgr.v1alpha1.PoolAdmin/DeletePool"
	PoolAdmin_GetPool_FullMethodName    = "/poolmgr.v1alpha1.PoolAdmin/GetPool"
	PoolAdmin_ListPools_FullMethodName  = "/poolmgr.v1alpha1.PoolAdmin/ListPools"
)

// PoolAdminClient is the client API for PoolAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PoolAdmin manages the CRUD lifecycle of pool definitions.
type PoolAdminClient interface {
	CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*Pool, error)
	UpdatePool(ctx context.Context, in *UpdatePoolRequest, opts ...grpc.CallOption) (*Pool, error)
	// DeletePool deletes a pool and drains it: every VM the pool owns that is not leased is
	// deleted along with it. If any VM is leased the call fails with FAILED_PRECONDITION,
	// unless force is set. Once it returns OK the pool is gone; a microVM whose flintlock host
	// could not be reached is deleted in the background.
	DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*Pool, error)
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error)
}

type poolAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolAdminClient(cc grpc.ClientConnInterface) PoolAdminClient {
	return &poolAdminClient{cc}
}

func (c *poolAdminClient) CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*Pool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pool)
	err := c.cc.Invoke(ctx, PoolAdmin_CreatePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAdminClient) UpdatePool(ctx context.Context, in *UpdatePoolRequest, opts ...grpc.CallOption) (*Pool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pool)
	err := c.cc.Invoke(ctx, PoolAdmin_UpdatePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAdminClient) DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolAdmin_DeletePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAdminClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*Pool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pool)
	err := c.cc.Invoke(ctx, PoolAdmin_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolAdminClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoolsResponse)
	err := c.cc.Invoke(ctx, PoolAdmin_ListPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolAdminServer is the server API for PoolAdmin service.
// All implementations should embed UnimplementedPoolAdminServer
// for forward compatibility.
//
// PoolAdmin manages the CRUD lifecycle of pool definitions.
type PoolAdminServer interface {
	CreatePool(context.Context, *CreatePoolRequest) (*Pool, error)
	UpdatePool(context.Context, *UpdatePoolRequest) (*Pool, error)
	// DeletePool deletes a pool and drains it: every VM the pool owns that is not leased is
	// deleted along with it. If any VM is leased the call fails with FAILED_PRECONDITION,
	// unless force is set. Once it returns OK the pool is gone; a microVM whose flintlock host
	// could not be reached is deleted in the background.
	DeletePool(context.Context, *DeletePoolRequest) (*emptypb.Empty, error)
	GetPool(context.Context, *GetPoolRequest) (*Pool, error)
	ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error)
}

// UnimplementedPoolAdminServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolAdminServer struct{}

func (UnimplementedPoolAdminServer) CreatePool(context.Context, *CreatePoolRequest) (*Pool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePool not implemented")
}
func (UnimplementedPoolAdminServer) UpdatePool(context.Context, *UpdatePoolRequest) (*Pool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePool not implemented")
}
func (UnimplementedPoolAdminServer) DeletePool(context.Context, *DeletePoolRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePool not implemented")
}
func (UnimplementedPoolAdminServer) GetPool(context.Context, *GetPoolRequest) (*Pool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedPoolAdminServer) ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPools not implemented")
}
func (UnimplementedPoolAdminServer) testEmbeddedByValue() {}

// UnsafePoolAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolAdminServer will
// result in compilation errors.
type UnsafePoolAdminServer interface {
	mustEmbedUnimplementedPoolAdminServer()
}

func RegisterPoolAdminServer(s grpc.ServiceRegistrar, srv PoolAdminServer) {
	// If the following call pancis, it indicates UnimplementedPoolAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolAdmin_ServiceDesc, srv)
}

func _PoolAdmin_CreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAdminServer).CreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAdmin_CreatePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAdminServer).CreatePool(ctx, req.(*CreatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAdmin_UpdatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAdminServer).UpdatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAdmin_UpdatePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAdminServer).UpdatePool(ctx, req.(*UpdatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAdmin_DeletePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAdminServer).DeletePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAdmin_DeletePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAdminServer).DeletePool(ctx, req.(*DeletePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAdmin_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAdminServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAdmin_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAdminServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolAdmin_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolAdminServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolAdmin_ListPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolAdminServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolAdmin_ServiceDesc is the grpc.ServiceDesc for PoolAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poolmgr.v1alpha1.PoolAdmin",
	HandlerType: (*PoolAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePool",
			Handler:    _PoolAdmin_CreatePool_Handler,
		},
		{
			MethodName: "UpdatePool",
			Handler:    _PoolAdmin_UpdatePool_Handler,
		},
		{
			MethodName: "DeletePool",
			Handler:    _PoolAdmin_DeletePool_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _PoolAdmin_GetPool_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _PoolAdmin_ListPools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poolmgr/v1alpha1/pooladmin.proto",
}
